name: podcasts_ofw
description: A Flutter app that plays one podcast per day

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  firebase_core: ^2.24.1
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.15.1
  provider: ^6.1.1
  go_router: ^12.1.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/